### ISSUE TITLE
Maximum call stack size exceeded when rendering Editable with Element/Leaf props

### ISSUE THREAD

**Issue by plitokpikin** [nathanfaucett/svelte-slate#2] opened 2022-05-10 05:43 UTC
![image](https://user-images.githubusercontent.com/33843607/167555747-e3bd22b5-e468-4f79-b4f9-20d5fee0be35.png)

The code is basic:
```svelte
<script>
let value = [{
	type: 'paragraph',
	children: [
		{ text: 'This is editable ' },
		{ text: 'rich', bold: true },
		{ text: ' text, ' },
		{ text: 'much', italic: true },
		{ text: ' better than a ' },
		{ text: '<textarea>', code: true },
		{ text: '!' }
	]
}];
</script>

...

<Slate {editor} bind:value>
    <Editable placeholder="Enter some text..." 
        {Element}
        {Leaf}      
    />
</Slate>
```

**Comment by nathanfaucett** [comment] 2022-05-10 11:20
can you share the Element and Leaf components you are using? my guess is that this is using https://github.com/nathanfaucett/svelte-slate/blob/main/src/lib/components/Element.svelte and https://github.com/nathanfaucett/svelte-slate/blob/main/src/lib/components/Leaf.svelte which are the internal renderers for the elements, the Editable takes components like the ones here https://github.com/nathanfaucett/svelte-slate/blob/main/src/example/Element.svelte and https://github.com/nathanfaucett/svelte-slate/blob/main/src/example/Leaf.svelte, if this is the case it might make sense to rename those internal components

**Comment by plitokpikin** [comment] 2022-05-10 13:52
True, I'm importing the `src/lib` components, as opposed to `src/example` ones.
The thing is, only `src/lib` components are exposed in the package, the `src/example` folder is not included at all.

**Comment by nathanfaucett** [comment] 2022-05-10 22:08
yeah I think I will change the names of the internal components for now, the examples are really just for reference so you can write your own

**Comment by nathanfaucett** [comment] 2022-05-14 02:14
closing this issue as it is not a bug but an issue of poor naming, renamed in https://github.com/nathanfaucett/svelte-slate/commit/8db1c5aeb48bbd78e586dab094ce040803ac51d1

**Closed as completed by nathanfaucett** 2022-05-14 02:14 UTC
