### ISSUE TITLE
triple click bug

### ISSUE THREAD

**Issue by jnath** [nathanfaucett/svelte-slate#3] opened 2022-06-30 12:38 UTC
hello i have a bug reported on react-slate but not reported in svelte-slate
https://github.com/ianstormtaylor/slate/pull/4914

for test

https://svelte.dev/repl/b2fd358f082b444d873f95a8dedaf1ea?version=3.48.0

triple click on text 

bug: no line selected

**Comment by nathanfaucett** [comment] 2022-07-07 22:46
Not sure if this is an issue with the svelte repl compiler or not but I do not get an error here https://nathanfaucett.github.io/svelte-slate/default

**Comment by nathanfaucett** [comment] 2022-07-22 10:46
closing this issue, since I can not reproduce it, and it does not happen on any of the example pages.

**Closed as completed by nathanfaucett** 2022-07-22 10:46 UTC
